---
- name: Set facts for docker container with backend
  set_fact:
    uwsgi_processes: "{{ (uwsgi_processes is defined) | ternary(uwsgi_processes, 4) }}"
    deploy_env: "{{ deploy_environment | default('Development') }}"
    test_ip_addr: "{{ test_ip_address | default('') }}"
    sentry_disabled: "{{ (deploy_environment is defined and deploy_environment == 'Production') | ternary('False', 'True') }}"
    published_ports: "{{ (deploy_environment is defined and deploy_environment == 'Production') | ternary(['127.0.0.1:{{ backend_port }}', uwsgi_port] | join(':'), [backend_port, uwsgi_port] | join(':')) }}"


- name: Up the backend container from docker image
  docker_container:
    name: "{{ container_env_prefix }}_backend"
    image: "almalinux/mirror_service:latest"
    state: started
    restart: yes
    restart_policy: unless-stopped
    pull: yes
    hostname: backend
    networks:
      - name: backend
    env:
      GEOIP_PATH: "/mirrors/geoip_db.mmdb"
      ASN_PATH: "/mirrors/asn_db.mmdb"
      SQLITE_PATH: "/data/mirrors.db"
      UWSGI_PROCESSES: "{{ uwsgi_processes | string }}"
      SENTRY_DSN: "{{ sentry_dsn | string }}"
      PYTHONPATH: "/src/app"
      DEPLOY_ENVIRONMENT: "{{ deploy_env | string }}"
      TEST_IP_ADDRESS: "{{ test_ip_addr | string }}"
      AUTH_KEY: "{{ auth_key | string }}"
      SENTRY_DISABLED: "{{ sentry_disabled | string }}"
      UWSGI_ADDRESS: "{{ uwsgi_address | string }}"
      UWSGI_PORT: "{{ uwsgi_port | string }}"
      REDIS_PORT: "{{ redis_port | string }}"
      REDIS_HOST: "{{ redis_host | string }}"
    published_ports:
      - "{{ published_ports }}"
    mounts:
      - source: "{{ source_path }}/src/backend"
        target: "/src/app"
        read_only: yes
        type: bind
      - source: "{{ config_root }}/mirrors"
        target: "/mirrors"
        read_only: no
        type: bind
      - source: "{{ config_root }}/data"
        target: "/data"
        read_only: no
        type: bind
    log_driver: "json-file"
    log_options:
      max-size: "200m"
      max-file: "5"
