---

- name: Up the redis container from docker image
  docker_container:
    name: "{{ container_env_prefix }}_redis"
    image: "redis:6.0.3"
    state: started
    restart: yes
    restart_policy: unless-stopped
    pull: yes
    hostname: "{{ redis_host }}"
    networks:
      - name: backend
    published_ports:
      - "127.0.0.1:{{ redis_port }}:{{ redis_port }}"
    command: "redis-server --appendonly yes --port {{ redis_port }}"
    mounts:
      - source: "redis_data"
        target: "/data"
        read_only: no
        type: volume
    log_driver: "json-file"
    log_options:
      max-size: "200m"
      max-file: "5"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 1m
